### ISSUE TITLE
New Unstable Affliction Mechanics

### ISSUE THREAD

**Issue by Thilitium** [rgd87/NugRunning#14]
With 7.1 wow update, unstable affliction mechanics have changed, there is now 5 different spell id, one for each stackable UA (max is 5 at a time).
I've come up with the following solution :
Spell( 233490 ,{ name = "", scale = 0.6, duration = 8,  priority = 10, nameplates = true, ghost = True, color = colors.GREEN })
Spell( 233496 ,{ name = "", scale = 0.6, duration = 8,  priority = 10, nameplates = true, ghost = True, color = colors.GREEN })
Spell( 233497 ,{ name = "", scale = 0.6, duration = 8,  priority = 10, nameplates = true, ghost = True, color = colors.GREEN })
Spell( 233498 ,{ name = "", scale = 0.6, duration = 8,  priority = 10, nameplates = true, ghost = True, color = colors.GREEN })
Spell( 233499 ,{ name = "", scale = 0.6, duration = 8,  priority = 10, nameplates = true, ghost = True, color = colors.GREEN })

It would be nice if the 5 spells could be stacked into one bar, but I do not know if it is possible and how to do that.
Thank you for this wonderful addon which has made me love playing affliction even more than I already do.
Have a good day.

**Comment by d87** [comment]
Made additional UAs minimized https://github.com/rgd87/NugRunning/commit/756bf1097f47d1f42cec0463f1ec7be335900d6d
