### ISSUE TITLE
Unstable affliction timer

### ISSUE THREAD

**Issue by Thilitium** [rgd87/NugRunning#16]
Hello!
It seems that the affliction timer is a little bit broken. It is sometimes longer than in reality. It is probably due to haste trinket procs. If you cast multiple UA while proccing haste and wait for the first one to finish (in reality), the timer on the addon for the remaining UA's will then update, but still not correctly. I could upload a quick video to show the issue more clearly if needed, just let me know.
Thank you !

**Comment by d87** [comment]
uhh... i guess i could use a video, but
1) addon tries to always display durations from target unit, and as far as i can tell UA timers properly end at the same time when they are ending on target frame.
2) if it can't acquire data from target or mouseover or focus it will use default duration, which is 8, and update when it becomes possible (maybe you're referring to this)

i don't exactly remember how haste procs interact with aura times, but i think the important part is that auras always end with the last tick
