### ISSUE TITLE
Rogue riposte error when disabled

### ISSUE THREAD

**Issue by IzzuCG** [rgd87/NugRunning#19]
Disabled the Riposte skill notification on my rogue. Every time I parry (which would activate it if it was active), I get the following LUA error. No error if I leave it active:

> Message: Interface\AddOns\NugRunning\NugRunning.lua:518: attempt to index local 'timer' (a nil value)
> Time: Thu May 30 23:47:01 2019
> Count: 27
> Stack: Interface\AddOns\NugRunning\NugRunning.lua:518: attempt to index local 'timer' (a nil value)
> Interface\AddOns\NugRunning\NugRunning.lua:518: in function `SPELL_ACTIVATION_OVERLAY_GLOW_SHOW'
> Interface\AddOns\NugRunning\NugRunning.lua:350: in function <Interface\AddOns\NugRunning\NugRunning.lua:345>
> (tail call): ?
> 
> Locals: self = NugRunning {
>  RemoveDose = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:976
>  UpdateAllNameplateTextures = <function> defined @Interface\AddOns\NugRunning\frame.lua:279
>  nameplate_timers = <table> {
>  }
>  CreateCastbarTimer = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:2316
>  GetUnitAuraData = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1155
>  MakeName = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1041
>  SPELL_ACTIVATION_OVERLAY_GLOW_HIDE = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:534
>  PreGhost = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1522
>  ACTIVE_TALENT_GROUP_CHANGED = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1614
>  SetupSpecialTimers = <function> defined @Interface\AddOns\NugRunning\special.lua:137
>  UnitAffiliationCheck = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:2162
>  dotpowerFrame = <unnamed> {
>  }
>  free = <table> {
>  }
>  PLAYER_LOGIN = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:246
>  ActivateTimer = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:659
>  queueFrame = <unnamed> {
>  }
>  db = <table> {
>  }
>  SetupDefaults = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:171
>  SlashCmd = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:2058
>  COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:442
>  anchors = <table> {
>  }
>  SetUnitAuraValues = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1105
>  QueueAura = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1085
>  CHARACTER_POINTS_CHANGED = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1614
>  GhostFunc = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1292
>  SPELL_UPDATE_COOLDOWN = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:639
>  UpdateAllTextures = <function> defined @Interface\AddOns\NugRunning\frame.lua:274
>  UpdateUnitAuras = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:2174
>  UpdateAllFonts = <function> defined @Interface\AddOns\NugRunning\frame.lua:269
>  UNIT_POWER_UPDATE = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:2448
>  GhostExpire = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1281
>  cooldownTicker = <table> {
>  }
>  DeactivateTimer = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:998
>  ConstructTimerBar = <function> defined @Interface\AddOns\NugRunning\frame.lua:429
>  Commands = <table> {
>  }
>  SPELL_ACTIVATION_OVERLAY_GLOW_SHOW = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:507
>  TimerFunc = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1181
>  SPELL_UPDATE_USABLE = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:345
>  timers = <table> {
>  }
>  active = <table> {
>  }
>  DeactivateTimersOnDeath = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1022
>  Unlock = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1647
>  cpNow = 0
>  cpWas = 2
>  SetDefaultDuration = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1033
>  SetupArrange = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1397
>  0 = <userdata>
>  DoNameplates = <function> defined @Interface\AddOns\NugRunning\nameplates.lua:8
>  ClearTimers = <function> defined @Interface\AddOns\NugRunning\NugRunning.lua:1638
>  RemoveDefaultsPreserve = <function> defined @Interface\AddOns\NugRunni

**Comment by d87** [comment]
ok, fixed in https://github.com/rgd87/NugRunning/commit/08f7be5fcbcd36a9185ab64c47dceea87031c1e5
btw, does Riposte still pops up even if you haven't learned it? Or you disabled it for some other reason?

**Comment by IzzuCG** [comment]
It still pops up even if I don't have it. That's the main reason I was disabling it.

**Comment by d87** [comment]
Oh, that's bad. Anyway, fixed both in the newest release on wowi

**Comment by IzzuCG** [comment]
Well, in that case, it's doing the same thing with Ghostly Strike. No error if I disable it, though.

**Comment by d87** [comment]
Need more info on that, because Ghostly Strike is a completely different case. The only way it would randomly appear is if something else makes it go on cooldown that is longer than gcd.

**Comment by IzzuCG** [comment]
Sorry for the late response, but I believe you're right. I can only replicate this when I pop stoneform. Seems to be a 1-1.5s CD after using stoneform.

**Comment by d87** [comment]
fixed it now
