### ISSUE TITLE
Chill/slow effects

### ISSUE THREAD

**Issue by Olorun** [rgd87/NugRunning#20]
Would be nice if we could track Improved Blizzard (mage talent) and Chilled (from mage Frost Armor) effects.

**Comment by d87** [comment]
Isn't blizzard like 1.5s long?

**Comment by Olorun** [comment]
Yeah 4.5 seconds with permafrost, and pretty useful to track since then you can time your Cone of Cold cast right when it falls off (useful for AoE grinding)

**Comment by d87** [comment]
done

**Comment by d87** [comment]
I checked this myself on AV realm today and Improved Blizzard debuff simply doesn't appear in combat log, so there won't be a timer for it, nothing can be done
