### ISSUE TITLE
Nameplate Timers

### ISSUE THREAD

**Issue by Olorun** [rgd87/NugRunning#21]
On Musclebrah's stream, I've seen timers over the nameplates looking quite nice (https://imgur.com/a/n5HXvfV), and I'm pretty sure he set it up using NugRunning..but I couldn't recreate it. Any idea how to make it look like in the picture? (frostbolt timer over the nameplate)

**Comment by d87** [comment]
NugRunning has a nameplate functionality, but it's bars, not icons. You can try enabling that in frostbolt's spell settings and see if that's good enough for you.
He's using some weird weakaura that mods nameplates, and i doubt it is utilizing nugrunning.

Anyway... what I would do is just get any working nameplate addon with aura display, and make it use https://github.com/rgd87/LibClassicDurations
Then optionally add OmniCC for numeric counter

**Comment by Olorun** [comment]
Ah alright! Don't think there are any good nameplate addons working well for the beta client yet, KuiNameplates seems to be lacking some functionality

**Comment by d87** [comment]
Check back later, I'll make a proper Kui plugin for LCD and post it here

**Comment by d87** [comment]
https://www.dropbox.com/s/pag0corllta0shg/KUI_LCD_classic.zip?dl=0

**Comment by Olorun** [comment]
Damn, you're my hero! Thanks for the help, appreciate it :)
