### ISSUE TITLE
Feature request: Improved Blizzard slow tracking

### ISSUE THREAD

**Issue by Olorun** [rgd87/NugRunning#22]
Would be nice to have this for Classic launch for AoE leveling mage

**Comment by d87** [comment]
You'll have to add it yourself, I don't have a mage on beta and
Basically add a new event timer for SPELL_PERIODIC_DAMAGE of with blizzard's id (use /nrun debug to find out the exact events), set it to be either multi-taget or set max timers to 1

**Comment by Olorun** [comment]
Alright, I'll try that! Thanks for the advice
