### ISSUE TITLE
Classic WoW enemy debuff timers no longer working as of 8/8/2019 Stress Test

### ISSUE THREAD

**Issue by rkschroe812** [rgd87/NugRunning#23]
Self buff timers continue to work just fine.

Enemy debuffs/dot timers no longer display, debug mode shows a duration of 0 for immolate/corruption.

Supposedly Blizz removed SpellId from the combat log, this may be the root of the issue.

**Comment by d87** [comment]
have you tried the latest version? i fixed it yesterday.
