### ISSUE TITLE
Should NugRunning display frames for switching target?

### ISSUE THREAD

**Issue by Casperlet** [rgd87/NugRunning#25]
NugRunning is so good that I've used it for years.

Should it display a frame for each dotted target above the dots timer? So I can click the frame to switch the current target among them, not press TAB again.

Thanks.

**Comment by d87** [comment]
No, everything that is related to targeting and casting spells is heavily restricted. If it wasn't you would be able to move different buttons under your mouse cursor in combat and make bots.
So it's either nameplates or tabbing
Try unchecking "Fixed Target Group" in settings, it makes tabbing easier and is probably better for true multidotting classes.

**Comment by Casperlet** [comment]
Sure, thank you.
