### ISSUE TITLE
In game dot timers

### ISSUE THREAD

**Issue by unbreakablechaos** [rgd87/NugRunning#26]
The ingame dottimers are locked and will not move. Im not sure if theres a command to fix it but i am having no luck. Is this a bug or is there a way i can fix this myself

**Comment by d87** [comment]
ESC -> Interface -> Addons

**Comment by unbreakablechaos** [comment]
Thats just how i turn it on and off im asking how to actually move the display screen where it shows them counting down. there in the middle of my screen.

**Comment by unbreakablechaos** [comment]
Is there a /command list i can use to bring these options up and fix it?

**Comment by unbreakablechaos** [comment]
Nevermind im an idiot thanks for helping

**Comment by unbreakablechaos** [comment]
oh nope i still cant move it in even interface. can you not move the text box with timers?
