### ISSUE TITLE
Issue with in game Dot timers

### ISSUE THREAD

**Issue by unbreakablechaos** [rgd87/NugRunning#27]
Will not let me move the ingame dot timers from the middle of my screen.

**Comment by d87** [comment]
move the red dot, jesus

**Comment by croana** [comment]
It would be useful if you could add the information about the red dot to the addon description on curse/wowinterface. I had to come to this issues page because I was having the same issue. Most addons are simply click and drag from anywhere when you unlock them.

**Comment by d87** [comment]
alright, but i was under the impression that it appearing after unlocking might give you a hint.
