### ISSUE TITLE
Wow Classic - Enrage Timer

### ISSUE THREAD

**Issue by tylerbrown47** [rgd87/NugRunning#32]
Enrage Spell ID 5229 not appearing.  I thought it may have something to do with improved enrage so I added https://classic.wowhead.com/spell=17080/improved-enrage and https://classic.wowhead.com/spell=17081/improved-enrage to the additional spell ids, bar still not showing up.  When I use /nrun listauras it lists id 5229 which is what the default is set to.  Not sure what the issue is.

**Comment by d87** [comment]
https://github.com/rgd87/NugRunning/releases/download/1.13.35/NugRunning-1.13.35-classic.zip
try this

**Comment by tylerbrown47** [comment]
Confirmed fixed, thanks!
