### ISSUE TITLE
Classic - unit name instead of spell name

### ISSUE THREAD

**Issue by Faesh** [rgd87/NugRunning#34]
Hey, I was wondering if its possible to display unit name instead of spell name on debuffs. 'Cause in this state I find the debuff timers pretty much useless.

**Comment by d87** [comment]
It's possible to edit spell configs similar to this
```lua
Spell( 41635 ,{ name = "Prayer of Mending", duration = 30, color = colors.TEAL3, textfunc = function(timer) return timer.dstName end })
```
https://github.com/rgd87/NugRunning/wiki/NugRunningUserConfig
otherwise no
