### ISSUE TITLE
[classic] Assignment of Spells to anchors

### ISSUE THREAD

**Issue by niph** [rgd87/NugRunning#35]
In the classic version all spells are assigned per default to one anchor. Is there an option to assign spells via the UI to another anchor?

Basically I would like to rearrange the anchors and assign spells so I can rearrange them on my UI instead of having one giant list of procs, buffs and debuffs. 

```
[buffs, procs]                                      [debuffs]
[player frame]                                    [target frame]

                            [cooldowns]
```

**Comment by d87** [comment]
spells are assigned to groups, groups to anchors
Use these commands for more info
/nrun
/nrun listgroups

**Comment by niph** [comment]
thanks, could solve it by assigning the default groups to other anchors via `/nrun groupset group=player  anchor=secondary`. Would be amazing to have an UI option for that in a future release. Otherwise thanks for the awesome addon.
