### ISSUE TITLE
Unstable Affliction

### ISSUE THREAD

**Issue by scotto88** [rgd87/NugRunning#36]
I use NugRunning for my warlock and since the prepatch, it won't display the timer bar for Unstable Affliction. I know this spell was changed in prepatch but I am not sure what to do to get NugRunning to display it. All my other warlock DOT's are tracking as normal.
![UA](https://user-images.githubusercontent.com/58789561/96071702-4b70bf80-0e68-11eb-8586-233e3fabfd41.PNG)

**Comment by d87** [comment]
That's weird, it should be working and it does work on my warlock.
Try applying it and then type /nrun listauras target
Is the spell id 316099? If not, what talents you have?
And if yes then try resetting all settings with
```/script NRunDB_Global = nil; ReloadUI();```

**Comment by d87** [comment]
I found it, when pvp talent for UA on 3 targets is picked spell id is different.

**Comment by scotto88** [comment]
Yes, I also had the 3 target UA talent selected last night when playing last night with my warlock. Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: d87 <notifications@github.com> Date: 10/15/20  2:55 AM  (GMT-06:00) To: rgd87/NugRunning <NugRunning@noreply.github.com> Cc: scotto88 <scottowens77@gmail.com>, Author <author@noreply.github.com> Subject: Re: [rgd87/NugRunning] Unstable Affliction (#36) 
I found it, when pvp talent for UA on 3 targets is picked spell id is different.

**Comment by scotto88** [comment]
Yes, I also had the 3 target UA talent selected last night when playing last night with my warlock.

**Comment by d87** [comment]
https://github.com/rgd87/NugRunning/releases/tag/9.0.2

**Comment by scotto88** [comment]
Thank you for the quick response and fixing the issue!
