### ISSUE TITLE
Guild interface interference 

### ISSUE THREAD

**Issue by zabeck** [rgd87/NugRunning#37]
A common issue I find with NugRunning is that it randomly interferes with guild management. Updating player and officer notes, as well as guild ranks is constantly blocked by the addon and I need to disable it to make the changes.
Attached is the message I get when the interference occurs.

![image_2020-12-10_162403](https://user-images.githubusercontent.com/62957282/101831581-1e592a00-3b04-11eb-8f4b-497cf495d04c.png)

**Comment by d87** [comment]
There's a thing called taint in wow (when you overwrite something in default ui) and it works in mysterious ways. When it spreads you get that dialog and this guild permissions problem is a common one. But basically maybe some other addon that is using Ace3 libs is somehow tainting something. Then the addon that first loaded Ace3 gets blamed for it.
And it may seem like why then if you disable NugRunning it starts working? But the important thing is you reloaded the UI and taint hasn't spread YET. You might as well not disable anything and just /reload and it'll work for a while too

NugRunning itself doesn't even deal with the default UI in any way, especially guild stuff

You can try using this to trace the problem further https://wow.gamepedia.com/CVar_taintLog
But i doubt it'll be helpful

**Comment by zabeck** [comment]
Thank you for replying, I'll give your idea a try and see what happens.
