### ISSUE TITLE
Id error for Vampiric Touch

### ISSUE THREAD

**Issue by acpirience** [rgd87/NugRunning#41]
Hello,
on the current PTR, Vampiric touch ID is 39416 and not 39414 as it is configured in the TBC beta4 addon.

Regards.

**Comment by d87** [comment]
that's just different spell ranks. But there was another issue with spell haste, so try https://github.com/rgd87/NugRunning/releases/tag/9.0-tbc-beta5

**Comment by acpirience** [comment]
This looks good to me, thanks.
