### ISSUE TITLE
nugRunning-9.1-bcc1  attempt to perform  arithmetic on local 'time' (a function value)

### ISSUE THREAD

**Issue by relaxedSoul** [rgd87/NugRunning#42]
Hello!

I uncountered a problem in the current version of the addon. 
I am using the following build: 

This is a text of an error: 
`Message: Interface\AddOns\NugRunning\NugRunning.lua:781: attempt to perform 
arithmetic on local 'time' (a function value)
Time: Thu May 20 18:41:59 2021`

Error details are attached to the file 
[nugRunning-9.1-bcc1 error.txt](https://github.com/rgd87/NugRunning/files/6517352/nugRunning-9.1-bcc1.error.txt)

Please can you review and fix it? It is crashing every fight. 
Your addon is very useful and my Shadow priest would be grateful if you could help

**Comment by d87** [comment]
Fixed in 9.1-bcc2, but do you use userconfig file for VT or SWP?

**Comment by relaxedSoul** [comment]
I will try to get some testing today or on the weekends. There were more errors than only this one. 

It would be best to have your addon working at the beginning of June. 

Thanks for this fix anyway!
