### ISSUE TITLE
Refresh target's debuffs only after casting new one

### ISSUE THREAD

**Issue by relaxedSoul** [rgd87/NugRunning#43]
Hello!

After updating to the latest build (NugRunning-9.1-bcc2.zip) I found new bug which wasn't present earlier.

Usecase:
1. I start the battle with first enemy A, cast SWP. 
Nugg: shows 1 debuff on the target.
2. Change the target to the second enemy B, 
Nugg: shows 1 debuff on the list of subtargets. Shows debuff is not present VT (vampiric Touch). 
3. Cast SWP on enemy B. 
Nugg: shows 1 debuff on the list of subtargets. Shows 1 debuff on the target.
4. Switch back to enemy A.
(BUG)
Nugg: shows 1 debuff (on enemy B) on the list of subtargets. Showns 0 debuffs on the target (enemy A).
5. Switch back to enemy B.
(BUG)
Nugg: shows 0 debuffs on any enemy. 

When I have 3 targets and rapidly switch enemies and cast Mind Flay on each of them sequatially, the debuffs sometimes are shown properly. 

Attaching screenshot with the bug. You can see nameplates with my debuffs. At the same time on the right corner of the screen is shown nugg. It has an almost empty list of debuffs on the enemies. 
![image](https://user-images.githubusercontent.com/3224471/119128017-c2dd8180-ba3d-11eb-9846-bce1e6a9550a.png)

Notes: my SWP and VT debuff settings are modified, but without hiding effects. I added highlighting and rotations for the elapsed time.

**Comment by d87** [comment]
fixed in 9.1-bcc3
