### ISSUE TITLE
Modified version request : CCTracker

### ISSUE THREAD

**Issue by Macumbafeh** [rgd87/NugRunning#49]
Hello Nug !

I'm happy to write to you again, i like your addons !

I want to ask you if it's possible to modify Nugrunning (and maybe rename it idk) to a CCTracker, like the old CCTracker made by Shadowed : https://www.curseforge.com/wow/addons/cc-tracker

What does it do :
- Only tracks CC spells mainly for arena and instances (sheep, sap, stuns, cyclone, roots....)
- Apply normal timer on mob but apply PvP timer on Player with DR.
- It tracks spells of any unit around, not only the player (friendly and enemies)

It's really like NugRunning but not for the player only.
So first of all, i play on tbc classic and i want to know if, with the new api, it's doable?

Thanks

NB : I tried it with Weak Aura already, and the Multi-target feature can't track everything properly, sometimes it bug out and i have an icon with no timer, or an icon stuck. On the Weak Aura discord they said it to me that it can't track it very well.

**Comment by d87** [comment]
You'd need to edit config.lua
1) remove ```if class == "WARLOCK then ... end``` lines to load spells from all classes all the time
2) Remove all non-CC spells
3) On CC spells set affiliation to Raid or Any in each spell settings and it'll show everything from all sources.
Nugrunning in tbc like on retail doesn't count DRs itself, just relies on correct data from nameplates.

But in general it's just a bad idea, you should display CCs on nameplates with addon like BigDebuffs or I even have my own NugPlateAuras

**Comment by Macumbafeh** [comment]
Thanks a lot for fast reply.
I use NugPlateAura yep !

But i want to track CC duration if i'm far too. Because if there is no nameplate i can't track it.

Also in instance sometimes there is so many nameplate, so it's easier to track a CC via an addon like that.

Why it's a bad idea for you? What is the problem?

**Comment by Macumbafeh** [comment]
> You'd need to edit config.lua
> 
> 1. remove `if class == "WARLOCK then ... end` lines to load spells from all classes all the time
> 2. Remove all non-CC spells
> 3. On CC spells set affiliation to Raid or Any in each spell settings and it'll show everything from all sources.
>    Nugrunning in tbc like on retail doesn't count DRs itself, just relies on correct data from nameplates.
> 
> But in general it's just a bad idea, you should display CCs on nameplates with addon like BigDebuffs or I even have my own NugPlateAuras

It doesn't work : / i guess it's config.tbc.lua and not config.lua
and i'm not sure for the 3. is it like this?
i added : affiliation = "raid"
![image](https://user-images.githubusercontent.com/47739411/144813957-5211144b-65dc-42df-baf6-405881c32f03.png)

ty !

**Comment by Macumbafeh** [comment]
Works perfect ! thanks

**Comment by Macumbafeh** [comment]
Just in case of, i've tested all the spells i use with your addon. And some spellID wasn't correct for tbc.
Btw it's just about the CC spells. if you want the modified version let me know.
