### ISSUE TITLE
[Wrath Classic] Death Knight Spells

### ISSUE THREAD

**Issue by Road-block** [rgd87/NugRunning#53]
I tried to add them using the in-game GUI but addon errors on opts.maxstack.

So can we get 

- Bone Shield (49222) and 
- Unbreakable Armor (51271) 

 with their data added to config.wotlk.lua 😃 
 
 Something like this maybe?
```lua
Spell( 49222, { name = "Bone Shield", duration = 300, charged = true, maxcharge = 3, color = colors.FROZEN, group = "buffs", init = function(self)self.maxcharge = 3 + Glyph(57210)*1 end })
Spell( 51271, { name = "Unbreakable Armor", duration = 300, charged = true, maxcharge = 3, color = colors.FROZEN, group = "buffs" })
```

**Comment by Road-block** [comment]
Since we're on the subject of Death Knight spells, the next one doesn't error when adding manually but would still be nice to have.

- Desolation (63583, 66800, 66801, 66802, 66803)

buffs group

**Comment by d87** [comment]
Added, thanks
