### ISSUE TITLE
Wotlk Classic - Living bomb only appears on nameplate after targetted

### ISSUE THREAD

**Issue by JanezStupar** [rgd87/NugRunning#62]
When casting a living bomb using a mouseover macro the progress bar only appears on nameplate after the affected target is targeted explicitly.

Unlike seed of corruption or corruption which correctly appear on all nameplates even when cast using the mouseover macro.

The configuration of living bomb in my mages spell config is set same as corruption on my warlock.

**Comment by d87** [comment]
Remove "Single Target" from Living bomb's settings

**Comment by JanezStupar** [comment]
Thank you for your prompt response and thank you for your work. Your addon is one of the most important add-ons for me.

See the attached screenshot. It displays my living bomb timer config and four target dummies.

It clearly shows that the Living Bomb is active on 4 target dummies. I have targetted one for reference - so you can see how the timer is configured there.

![image](https://github.com/rgd87/NugRunning/assets/647445/61f0aaae-e43a-4ddf-83c0-ef0bcfed9c06)

**Comment by d87** [comment]
Alright, 10.1.5 should fix it

**Comment by JanezStupar** [comment]
Can confirm issue has been fixed.

You are amazing!
