### ISSUE TITLE
Classic Era HC Lua error upon new timer being created

### ISSUE THREAD

**Issue by coldcurve** [rgd87/NugRunning#63]
Having this LUA error pop up, seemingly after any buff/debuff appearing on classic era HC with latest NugRunning version. Love the addon, would appreciate a fix of some kind

Message: Frame:CreateTexture(): Couldn't find inherited node "-5"
Time: Fri Sep 15 13:06:33 2023
Count: 1
Stack: Frame:CreateTexture(): Couldn't find inherited node "-5"
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/NugRunning/nameplates.lua"]:103: in function `CreateNameplateTimer'
[string "@Interface/AddOns/NugRunning/nameplates.lua"]:205: in function `UpdateNPTimers'
[string "@Interface/AddOns/NugRunning/nameplates.lua"]:184: in function `Update'
[string "@Interface/AddOns/NugRunning/NugRunning.lua"]:1733: in function `ArrangeTimers'
[string "@Interface/AddOns/NugRunning/NugRunning.lua"]:1016: in function `ActivateTimer'
[string "@Interface/AddOns/NugRunning/NugRunning.lua"]:583: in function <Interface/AddOns/NugRunning/NugRunning.lua:552>
[string "=(tail call)"]: ?

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by d87** [comment]
fixed in 1.14.3
